#!/usr/bin/env python3

# pihole-dashboard-inky-clean-screen
# Copyright (C) 2021  santoru
# modified for inky by numbermonkey
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Gets the things it needs
import sys
import os
from inky import InkyPHAT
from PIL import Image

# The sole variable 
FILENAME = "/tmp/.pihole-dashboard-inky-output"

# This checks if the script is running as root. You need this to write to the screen
if __name__ == '__main__':
    if os.geteuid() != 0:
        sys.exit("You need root permissions to access E-Ink display, try running with sudo!")
    try:
        os.remove(FILENAME)
    except FileNotFoundError:
        pass

    os.mknod(FILENAME)

# Initialise the screen
inky_display = InkyPHAT("red")
inky_display.set_border(inky_display.WHITE)
# Set a default image
img = Image.new("P", (inky_display.WIDTH, inky_display.HEIGHT))
inky_display.set_image(img)
# Write it to the screen
inky_display.show()
